### ISSUE TITLE
Move tests into separate tests/ directory

### ISSUE THREAD

**Issue by jhachenbergerSIT** [david-a-wheeler/flawfinder#11]
In order to improve the project structure, I would propose to put all test-related files (e.g. `correct-results*.{txt,csv,html}`, `test*.{c,patch}` ) into a subdirectory (e.g.`tests/`). Eventually, putting the relevant makefile parts into a separate makefile within the test directory would even further improve the clarity of the overall project (or at least of the makefile).

What do you think about this change? As soon as you agree to the general idea, I will create a pull-request.

This approach seems to be backed by PyPA and most answers on SO tend to suggest a similar structure for Python-based projects:
* https://github.com/pypa/sampleproject
* https://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application

**Comment by david-a-wheeler** [comment]
This *does* make sense.  There are multiple tests, so moving them into a separate subdirectory is reasonable.  I thought about doing that early on, but early on there were few tests (so why bother)... but that argument is no longer true.

**Comment by david-a-wheeler** [comment]
A PR would be greatly appreciated!

**Comment by jhachenbergerSIT** [comment]
Thanks for your feedback (and the feedback to the other issues)!

I created a PR.

And sorry for the commit duplicate listed here. I forgot to rebase my feature branch  (since I already had done the work some time ago) before pushing and now had to force push the feature branch again. And now, I don't know how to remove the "old" commit from showing up here.
