### ISSUE TITLE
Move documentation into separate docs/ directory

### ISSUE THREAD

**Issue by jhachenbergerSIT** [david-a-wheeler/flawfinder#12]
Similar to #11, I would like to propose to move all documentation to a new subdirectory called `docs`. If I got it correctly, this directory will only contain `flawfinder.1`. This directory could also contain a makefile to build the documentation.

I admit, it might be disputed to create one directory containing one file, but I see it as an API for a new developer trying to join this project and reading (/searching) the documentation is probably one of the most important things in the beginning and should be as easy as possible. Additionally, a manpage is perhaps (! - this might be wrong) not the most prominent documentation language for a Python-based project and hence, makes it harder to spot it at first.

If you agree with this suggestion, I will create a pull-request with the related changes.

**Comment by david-a-wheeler** [comment]
I don't think creating a subdirectory for a single file is worthwhile.  Adding structure (like subdirectories) is good when structure will actually help.

**Comment by david-a-wheeler** [comment]
Thanks for the comment though!
