### ISSUE TITLE
Move source code into separate directory

### ISSUE THREAD

**Issue by jhachenbergerSIT** [david-a-wheeler/flawfinder#13]
Similar to #11 and #12, I would like to propose to move the source code (right now only `flawfinder`) into a separate folder called `flawfinder/`. This would lead to a directory structure which clearly separates source code, tests and documentation from meta data (such as Contribution.md, License etc.).

This structure is also used by e.g. [PyPa's sample project](https://github.com/pypa/sampleproject) or [Open Sourcing a Python Project the Right Way](https://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/).

**Comment by david-a-wheeler** [comment]
There's only 1 source file and I don't intend to change that (because that greatly simplifies installation when tools like pip are unavailable).  I don't see a value in creating subdirectories for single files, that's just extra unnecessary steps.
