### ISSUE TITLE
Construction of string literals without using plus operators

### ISSUE THREAD

**Issue by elfring** [david-a-wheeler/flawfinder#2]
I have noticed that [plus operators were specified between string literals of Python source code](https://github.com/david-a-wheeler/flawfinder/blob/e4f4d4a34bb8504923e15df2a981b20841843d03/flawfinder#L276 "Update candidate").
I find such specifications unnecessary because [the programming language “Python” supports such concatenation without the usage of extra operators directly](https://docs.python.org/3/reference/lexical_analysis.html#string-literal-concatenation "String literal concatenation").

**Comment by david-a-wheeler** [comment]
I am trying to make it clear in the code that these combinations are intentional.

**Comment by elfring** [comment]
I would find string literal constructions clear enough (and a bit more efficient) without extra plus operators.

**Comment by david-a-wheeler** [comment]
Okay, patches welcome.  Per CONTRIBUTING.md, use "make check" to ensure it works on python2 and python3, and run pylint ("make pylint").  Pylint will currently throw a few warnings, try to not add more.

**Comment by elfring** [comment]
>…, use "make check" to ensure it works …

* Does this command still completely work as expected in your test environment?
* I noticed that the following information is presented by the program “make 4.2.1-7.5” on my openSUSE system despite of my impression from recipe traces that the desired commands were successfully executed.
  * `make: *** [makefile:143: test_001] Error 1`
  * `make: *** [makefile:149: test_002] Error 1`

**Comment by elfring** [comment]
It seems that [another small software update was needed](https://github.com/david-a-wheeler/flawfinder/commit/59a4d42a33d95e461baa1792a2d9ee6c9b9ba276 "Update test values for version number").

**Comment by david-a-wheeler** [comment]
Yes, sorry, I fixed it yesterday. I only noticed it yesterday.

**Comment by david-a-wheeler** [comment]
This was merged a long time ago, but I forgot to close this issue. Closing now!
