### ISSUE TITLE
False positive 'shell' (CWE-78) for boost::system::error_code

### ISSUE THREAD

**Issue by czw** [david-a-wheeler/flawfinder#22]
I have the following line in a C++ header file:

    void HandleWrite(const boost::system::error_code &error);

Flawfinder gives me this output:

```
Agent.h:82:  [4] (shell) system:
  This causes a new program to execute and is difficult to use safely
  (CWE-78). try using a library call that implements the same functionality
  if available.
```

This is obviously wrong, it's just triggering on the word `system` even though it's just a namespace and not `system()`.

**Comment by david-a-wheeler** [comment]
Fair enough, but many other libraries use the word "system" indicate similar effects to `system()`.

I suppose in cases where it's *obviously* just a namespace (e.g., followed by "::") we could omit the warning.

**Comment by david-a-wheeler** [comment]
I've tweaked the master branch so "system::" is ignored. That was simple to do and I think resolves the false positive.

**Comment by david-a-wheeler** [comment]
That change will be in the next release.
