### ISSUE TITLE
Superfluous "possible use of current directory" warning when using LOAD_LIBRARY_SEARCH_SYSTEM32

### ISSUE THREAD

**Issue by sylveon** [david-a-wheeler/flawfinder#26]
When using `LOAD_LIBRARY_SEARCH_SYSTEM32` on `LoadLibraryEx`, the developer is explicitly telling the function to load the DLL *only* from the System32 folder, therefore the warning emitted on the following snippet:
```cpp
HMODULE user32 = LoadLibraryEx(L"user32.dll", nullptr, LOAD_LIBRARY_SEARCH_SYSTEM32);
```

is completely superfluous and even potentially misleading.

**Comment by david-a-wheeler** [comment]
Thanks for the report! I'm trying to stay off the computer for a few days for the holidays, but I'll look at this more soon. Thanks again!

**Comment by david-a-wheeler** [comment]
Okay, so if I understand you correctly, the goal is to report LoadLibraryEx *unless* it uses LOAD_LIBRARY_SEARCH_SYSTEM32 in parameter 3, correct? Sounds reasonable.

Care to write that pull request?

**Comment by sylveon** [comment]
Correct! I'm not sure how to proceed writing such a pull request however.

**Comment by david-a-wheeler** [comment]
I implemented it in the master branch; it'll be in the next release.

**Comment by sylveon** [comment]
Thank you! I feel like this could be improved a bit, but I'll submit a PR for it.
