### ISSUE TITLE
Using augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [david-a-wheeler/flawfinder#3]
I have noticed that [source code like “`var = var + X`” was specified at a few places](https://github.com/david-a-wheeler/flawfinder/blob/e4f4d4a34bb8504923e15df2a981b20841843d03/flawfinder#L451 "Update candidate") so far.
I suggest to [use augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") instead.

**Comment by david-a-wheeler** [comment]
I will take patches, but I'll note that the amount of performance gained really isn't worth the trouble. What is more important is improving its ability to detect real problems or to ignore false positives.

**Comment by elfring** [comment]
* Would you like to apply another regular expression for the proposed software transformation?
* I find that source code analysis approaches from this Python script point fundamental open issues out in comparison to other known software technology.

**Comment by david-a-wheeler** [comment]
I'm not sure what you mean.  If you like to propose a change to the software, then create a pull request with the proposed change.

**Comment by elfring** [comment]
* One transformation would affect a bit of software fine-tuning.
* Additional development considerations can become relevant for [the published information “Nevertheless, flawfinder is fundamentally a naive program; it doesn’t even know about the data types of function parameters, and it certainly doesn’t do control flow or data flow analysis …”](https://dwheeler.com/flawfinder/#how_work "How does Flawfinder work?").
  Something was achieved based on the application of regular expressions so far.

**Comment by david-a-wheeler** [comment]
Pull request #4 changes flawfinder to use augmented assignment statements.

**Comment by david-a-wheeler** [comment]
The changes were merged, I'm closing this matching issue.
