### ISSUE TITLE
Man install in 2.0.14 release

### ISSUE THREAD

**Issue by jubalh** [david-a-wheeler/flawfinder#30]
https://dwheeler.com/flawfinder/#downloading doesn't seem to have the 2.0.14 tarball.
The GitHub generated tarball appears to be missing the .ps files used in the `makefile`.
If I just use the setup.py I get: `can't copy 'flawfinder.1.gz': doesn't exist or not a regular file`

Since we only have the `flawfinder.1` but not the generated tarball made with the `makefile`.

Maybe I'm misunderstanding how it should work?

**Comment by david-a-wheeler** [comment]
Hmm, there may have been a problem in generating the new release. I switched systems and it *shouldn't* have mattered... but maybe it did. My apologies for the inconvenience!

I'll check this out. If I need to, I'll create a new "clean" release.

**Comment by david-a-wheeler** [comment]
I've released a new version, 2.0.15; throw away 2.0.14.

Please let me know if this works or does not work for you. It *should* work, but I'd rather get independent confirmation :-).

**Comment by jubalh** [comment]
2.0.15 works perfectly. Thank you!
