### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [david-a-wheeler/flawfinder#5]
I suggest to reuse a higher level build system than [your current make script](https://github.com/david-a-wheeler/flawfinder/blob/e4f4d4a34bb8504923e15df2a981b20841843d03/makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by david-a-wheeler** [comment]
Since there's already a makefile, the Autotools (specifically automake) would be the simplest to transition to. I even created a video tutorial on the autotools, so I'm quite familiar with it.

HOWEVER: What is the *goal*?  I want to use simple tools if there's no big advantage to more sophisticated tools.  The makefile is pretty simple.  Is there a specific example of what you think should be done?

@squinky86 - your thoughts would be welcome.

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.14/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by squinky86** [comment]
Flawfinder is the first python project I've worked with that has a makefile. Most python projects, in my experience, just worry about setup.py and let users/developers handle any special cases beyond that. I could see a build system being useful to check for tools like ps2pdf, but I see it as more of a reference with helpful shortcuts more than a "this is the only way to build the project" makefile.

Setuptools' setup.py is sufficient as the cross-platform build system, but I wouldn't be opposed to also supporting one of the other build systems. I'm more familiar with Autotools as well (https://www.gnu.org/software/automake/manual/html_node/Python.html).

**Comment by david-a-wheeler** [comment]
I think in this case the negatives of a bigger build system generator outweigh the positives.

Flawfinder is designed to be extremely easy-to-install in many situations. In particular, I want to support copy-single-file installations, where users can simply copy "flawfinder" where they want & have it "just work".  So I specifically forbid external dependencies other than the built-in libraries.  That means users can *ignore* the setup.py if they wish.  That also means that having a separate configuration tool is not going to work in this case.

This reasoning is specifically for this one tool. I use other systems on other projects, and I even created an autotools tutorial on Youtube, so I'm certainly familiar with other tools and find them useful. But in this case I'm trying to make things absurdly easy for users to install in a variety of circumstances, including when they cannot use pip.

So I appreciate the comments, but this would hamper end-user experience, which I think is more important.  Thanks!

**Comment by elfring** [comment]
I imagine that your software distribution goals can be achieved also by a collaboration with additional build tools.
