### ISSUE TITLE
[BUG][PRINTABLE STACK] Using gettext I can print the stack

### ISSUE THREAD

**Issue by gargantuadev** [david-a-wheeler/flawfinder#92]
Hello there,

The documentation claims that when the gettext() function takes a string as input, it treats it as a constant and flawfinder doesn't give false positives in that case.  Flawfinder knows about gettext (a common library for internationalized programs), and will treat constant strings passed through gettext as though they were constant strings; this reduces the number of false hits in internationalized programs.

This is correct, but trying to play with this library I was able to find an example that highlights a flaw in flawfinder (I was able to print the stack). The following is the code I was playing with:

```
#include <stdio.h>
#include <stdlib.h>
#include <libintl.h>
#include <locale.h>
#define _(STRING) gettext(STRING)
#define COSTANTDEFINE "CostantDefine"
static const char stringConstantStatic[] = "1";
const char stringConstant[] = "2";
char stringNotConstant[] = "3";
int main()
{
      /* Setting the i18n environment */
      setlocale (LC_ALL, "");
      bindtextdomain ("example", "/usr/share/locale/");
      textdomain ("example");
      /* Example of i18n usage */
      printf(gettext("%x %x %x %x %x %x violato")); // in this way I can
      print the stack
      printf(gettext(stringConstantStatic));
      printf(gettext(stringConstant));
      printf(gettext(stringNotConstant));
      printf(gettext(COSTANTDEFINE));
      return EXIT_SUCCESS;
}
```

The output is this one:

![{B04021A7-4360-49CE-B186-60C0F6A84F34}](https://github.com/user-attachments/assets/4e21d278-be2d-4531-a6da-f1408f82dc2e)

May you kindly assign this issue to me?

**Comment by david-a-wheeler** [comment]
printf(gettext("%x %x %x %x %x %x violato")) is a terrible idea, but not likely in practice except during debugging.

All tools have false+ and false-. Changing this would probably introduce too many other problems, for a relatively unlikely situation.

**Comment by david-a-wheeler** [comment]
Also, I don't "assign". If you create a pull request, I'll try to look at it.
